dev:
  debug: false
  version: 0.1
  maintainer:
    name: Théo Vidal
    link: exybore@becauseofprog.fr
bot:
  name: Bop Le Bricoleur
  id: 558337741281165332
  illustration: https://cdn.discordapp.com/app-icons/549219394513797130/f2bf63715a6d1e41aea422c3a9c67561.png?size=256
  website: https://github.com/BecauseOfProg/bop-le-bricoleur
  color: 14890803
  error_color: 12000284
database:
  address: localhost
  port: 25450
  database: bob
  auth_source: bob
cache:
  address: localhost
  port: 6379
